<html lang="en"><head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/svg+xml" href="/vite.svg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vite + React + TS</title>
    <script type="module" crossorigin="" src="/assets/index-Bno5s__0.js"></script>
    <link rel="stylesheet" crossorigin="" href="/assets/index-9v3p4yI-.css">
  </head>
  <body>
    <div id="root"><div class="min-h-screen bg-gray-50"><header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header><main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main></div></div>
  

</body></html>
  <head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/svg+xml" href="/vite.svg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vite + React + TS</title>
    <script type="module" crossorigin="" src="/assets/index-Bno5s__0.js"></script>
    <link rel="stylesheet" crossorigin="" href="/assets/index-9v3p4yI-.css">
  </head>
  <body>
    <div id="root"><div class="min-h-screen bg-gray-50"><header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header><main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main></div></div>
  

</body>
  <div id="root"><div class="min-h-screen bg-gray-50"><header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header><main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main></div></div>
  <div class="min-h-screen bg-gray-50"><header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header><main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main></div>
  <header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header>
  <main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main>
  <div class="min-h-screen bg-gray-50"><header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header><main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main></div>
  <div id="root"><div class="min-h-screen bg-gray-50"><header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header><main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main></div></div>
  <body>
    <div id="root"><div class="min-h-screen bg-gray-50"><header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header><main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main></div></div>
  

</body>
  <html lang="en"><head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/svg+xml" href="/vite.svg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vite + React + TS</title>
    <script type="module" crossorigin="" src="/assets/index-Bno5s__0.js"></script>
    <link rel="stylesheet" crossorigin="" href="/assets/index-9v3p4yI-.css">
  </head>
  <body>
    <div id="root"><div class="min-h-screen bg-gray-50"><header class="bg-white shadow-sm"><div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><h1 class="text-xl font-semibold text-gray-900">Заявки</h1><div class="flex items-center gap-4"><button class="relative"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-6 h-6 text-gray-600"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg><span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span></button><div class="relative"><button class="flex items-center gap-2 hover:bg-gray-100 p-2 rounded-md"><div class="w-8 h-8 rounded-full overflow-hidden"><img src="https://i.ibb.co/TqQ7PXL/a-l.jpg" alt="Profile" class="w-full h-full object-cover"></div><div class="text-left"><div class="font-medium">Рождественский.А.В</div><div class="text-sm text-gray-600">модератор</div></div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down w-4 h-4"><path d="m6 9 6 6 6-6"></path></svg></button></div></div></div></header><main class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-center mb-6"><div class="flex gap-4"><button class="px-4 py-2 rounded-full bg-indigo-600 text-white">Все (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">В ожидании (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Принято (0)</button><button class="px-4 py-2 rounded-full text-gray-600 hover:bg-gray-100">Отклонено (0)</button></div><button class="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus w-5 h-5"><path d="M5 12h14"></path><path d="M12 5v14"></path></svg>Новая заявка</button></div><div class="space-y-4"></div></main></div></div>
  

</body></html>
